### ISSUE TITLE
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by LLCF** [crizCraig/deepdrive#1]
PS C:\Program Files\DeepDrive\deepdrive> python install.py
I cannot download files, here is the results
```
Downloading https://www.dropbox.com/sh/fy6nha3ikm2ugij/AADm8SPKm5bX3Nl2qx69rCcYa
Traceback (most recent call last):
  File "install.py", line 118, in <module>
    sys.exit(main())
  File "install.py", line 114, in main
    setup(config, args)
  File "install.py", line 67, in setup
    install_stuff_that_goes_in_gtav_dir()
  File "install.py", line 59, in install_stuff_that_goes_in_gtav_dir
    utils.download_folder('https://www.dropbox.com/sh/fy6nha3ikm2ugij/AADm8SPKm5
  File "C:\Program Files\DeepDrive\deepdrive\utils.py", line 41, in download_fol
    location = urllib.urlretrieve(url)
  File "C:\tools\python2\Lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\tools\python2\Lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\tools\python2\Lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\tools\python2\Lib\urllib.py", line 457, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "C:\tools\python2\Lib\urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "C:\tools\python2\Lib\urllib.py", line 641, in http_error_302
    data)
  File "C:\tools\python2\Lib\urllib.py", line 667, in redirect_internal
    return self.open(newurl)
  File "C:\tools\python2\Lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\tools\python2\Lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\tools\python2\Lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\tools\python2\Lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\tools\python2\Lib\httplib.py", line 859, in send
    self.connect()
  File "C:\tools\python2\Lib\httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "C:\tools\python2\Lib\ssl.py", line 352, in wrap_socket
    _context=self)
  File "C:\tools\python2\Lib\ssl.py", line 579, in __init__
    self.do_handshake()
  File "C:\tools\python2\Lib\ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:590)
```

**Comment by twmht** [comment]
Perhaps this is the ssl lib issue.

**Comment by crizCraig** [comment]
@LLCF I saw you were running `run.py` in another issue. Were you able to resolve this?

**Comment by LLCF** [comment]
I have solved this problem.  China's great firewall limit the network connection
